name: Build Miku Calc APK
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Tools
      run: |
        pip install --upgrade buildozer cython git+https://github.com
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev
    - name: Build APK
      run: yes | buildozer -v android debug
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: MikuCalc-APK
        path: bin/*.apk
