name: Build Miku Calc APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Профессиональный автоматический робот-сборщик Kivy
      # Он сам скачает SDK, примет все лицензии Google и найдет aidl
      - name: Build APK with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1.4.1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MikuCalc-APK
          path: bin/*.apk
